### ISSUE TITLE
[regression] unicode file streams support missing

### ISSUE THREAD

**Issue by git-mf** [fsinapsi/avinaptic2#3]
hi,
i tried to open some files with non ascii characters filenames but couldn't, avinaptic (gui and cli) reported the files as not found.

on the other hand, unicode metadata is read correctly.

### avinaptic 2011-12-18
![image](https://user-images.githubusercontent.com/52412011/97786918-03170880-1baf-11eb-920d-6defd2f1acc3.png)

### avinaptic: _open error_
![image](https://user-images.githubusercontent.com/52412011/97787003-9f410f80-1baf-11eb-87a8-7e3dca8c9b07.png)

### avinaptic: _unicode metadata suport_ 
![image](https://user-images.githubusercontent.com/52412011/97787054-0c54a500-1bb0-11eb-8118-9516f864c0ac.png)

thanks 👍

**Comment by fsinapsi** [comment]
Hi,
thank you for the feedback!
It's a bug in the windows version (linux version is ok).
I have just tried [this method](https://sourceforge.net/p/mingw-w64/wiki2/Unicode%20apps/) but the result (in that sample code) is the following:

/usr/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: /usr/x86_64-w64-mingw32/lib/libmingw32.a(lib64_libmingw32_a-crt0_w.o): in function `wmain':
/build/mingw-w64-crt/src/mingw-w64-v8.0.0/mingw-w64-crt/crt/crt0_w.c:23: undefined reference to `wWinMain'
collect2: error: ld returned 1 exit status

Anyway, I'll try to fix it.
(Note: I'm using cross compiling from linux, so it's not so easy to debug...)

**Comment by fsinapsi** [comment]
I'm facing with some strangenesses:
![strangeness](https://user-images.githubusercontent.com/67010432/97799144-6bf09600-1c2c-11eb-90d2-abea9025dd2a.png)

**Comment by git-mf** [comment]
> 
> 
> I'm facing with some strangenesses:
> ![strangeness](https://user-images.githubusercontent.com/67010432/97799144-6bf09600-1c2c-11eb-90d2-abea9025dd2a.png)

hi,
i could test this version on my windows machine to see if it behaves the same way or it is just related to wine.

**Comment by fsinapsi** [comment]
I forgot to set [UTF8MODE_FILE in IUP](https://webserver2.tecgraf.puc-rio.br/iup/en/attrib/iup_globals.html):

"By default IUP uses file names in the current locale, even when UTF8MODE=Yes. To use UTF-8 file names in Windows set this attribute to Yes. Default: NO.

The main places affected by this attribute is IupFileDlg attributes, such as VALUE, FILE and DIRECTORY, and the DROPFILES_CB callback."

This should partially resolve the problem.
I have released avinaptic-win64-20201101.zip and avinaptic-win32-20201101.zip
I'll try to fix avinaptic2-cli...

**Comment by git-mf** [comment]
> 
> 
> I forgot to set [UTF8MODE_FILE in IUP](https://webserver2.tecgraf.puc-rio.br/iup/en/attrib/iup_globals.html):
> 
> "By default IUP uses file names in the current locale, even when UTF8MODE=Yes. To use UTF-8 file names in Windows set this attribute to Yes. Default: NO.
> 
> The main places affected by this attribute is IupFileDlg attributes, such as VALUE, FILE and DIRECTORY, and the DROPFILES_CB callback."
> 
> This should partially resolve the problem.
> I have released avinaptic-win64-20201101.zip and avinaptic-win32-20201101.zip
> I'll try to fix avinaptic2-cli...

i tested both flavors, they now can handle :ok_hand: correctly utf8 filenames.
i didn't get the point in `the problem being partially solved`

**Comment by fsinapsi** [comment]
> i didn't get the point in `the problem being partially solved`

you wrote "avinaptic (gui and **cli**) reported the files as not found"; avinaptic2-cli is not affected by last changes (and I haven't tested it yet)

**Comment by git-mf** [comment]
> 
> 
> > i didn't get the point in `the problem being partially solved`
> 
> you wrote "avinaptic (gui and **cli**) reported the files as not found"; avinaptic2-cli is not affected by last changes (and I haven't tested it yet)

my fault, the cli version (2020-10-26) was ok: i forgot to change the console active codepage.
sorry for the misleading info.

**Comment by fsinapsi** [comment]
thanks for the feedback!
yesterday I read "...to set the console code page to UTF-8 executing "chcp 65001" on the command line".
This explains the strange result of "wine test-win.exe ... | cat", I suppose.

**Comment by git-mf** [comment]
> 
> 
> thanks for the feedbacks!

thanks for your efforts :thumbsup:
